---
title: "Stock selection for 4 factor model"
author: "Kobus Viljoen"
date: "05 October 2016"
output: html_document
---

```{r}
knitr::opts_chunk$set(
  eval = FALSE)
```

##Necessary packages
```{r}
library(broom)
library(modelr)
library(ggplot2)
library(stringr)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(tibble)
```


##Grouping together the market cap and PE values for each share
```{r}
Fund <- function(df){
  df %>% bind_rows(.id="Ticker") %>%
  group_by(Ticker)
}

# map the function over the fundamentals and create a new tibble, fundamental all named Fund_all
Fund_all <- Fundamental_Data %>% mutate(FundData = map(Fund_Data,Fund))

# joining the market cap and volatility tibbles by date and ticker. Group by ticker and nest
MC <- Fund_all %>% filter(fields == "CUR_MKT_CAP") %>% select(FundData) %>% unnest()
EY <- Fund_all %>% filter(fields == "EARN_YLD_HIST") %>% select(FundData) %>% unnest()
PXLAST <- Fund_all %>% filter(fields == "PX_LAST") %>% select(FundData) %>% unnest()
GP <- Fund_all %>% filter(fields == "GROSS_PROFIT") %>% select(FundData) %>% unnest()
VOL <- Fund_all %>% filter(fields == "VOLATILITY_260D") %>% select(FundData) %>% unnest()
Fund_4FACTOR <- left_join(MC,EY) %>% 
  left_join(PXLAST) %>% 
  left_join(GP) %>% 
  left_join(VOL) %>% 
  group_by(Ticker) %>% 
  nest()
# Used so many left_joins due to the computer not being able to join with respect to date and ticker in this case without crashing.
```


## Selecting the stocks for each rebalancing date (semi-annual dates)
```{r}
# The semi annual dates are extracted from the halfyearly price data that was extracted from bloomberg
# [[2]] is the data corresponding to quarterly dates
# Company's ROE ratios began to feature on the JSE in the 2000's
dates <- close_prices$data[[2]] %>% 
  bind_rows(.id="Ticker") %>% 
  group_by(date) %>% 
  nest() %>% 
  filter(date >= date[14]) %>%
  select(date)

selection <- function(df1){
  all <- dates %>% mutate(sel = map(date,function(df){
    sel <- df1 %>% filter(date <= df) %>% filter(date >= df - years(1))
    tibble(date = sel$date , 
           EY_Z = (sel$EARN_YLD_HIST - mean(sel$EARN_YLD_HIST,na.rm = T))/sd(sel$EARN_YLD_HIST,na.rm = T),
           Tot_Ret = log(sel$PX_LAST) - log(sel$PX_LAST[1]),
           GP_Z = (sel$GROSS_PROFIT - mean(sel$GROSS_PROFIT,na.rm = T))/sd(sel$GROSS_PROFIT,na.rm = T),
           VOL = sel$VOLATILITY_260D,
           Market_Cap = sel$CUR_MKT_CAP) %>%
      filter(date == df)
    }))
  all$sel %>% bind_rows()
}

# The output:
ALL_FACTOR_model_Selection <- Fund_4FACTOR %>% mutate(selection = map(data,selection))

# Now i need to group the output according to the semi-annual dates.
# Once this is done, i can select the stocks according to some specified rule (4 factor model in this case)
ALL_FACTOR_Selection <- ALL_FACTOR_model_Selection$selection %>% 
  bind_rows(.id="Ticker") %>%
  mutate(Ticker = ALL_FACTOR_model_Selection$Ticker[as.numeric(Ticker)])

# The result is a tibble with the first column, the rebalancing dates. The second column is a list of tibbled containing each share's info corresponding to that specific date.
ALL_FACTOR_Selection <- ALL_FACTOR_Selection %>% 
  group_by(date) %>% 
  arrange(date) %>% 
  nest()

# Filtering the top 50% of a factor (Factor Tilt)
stocks <- function(df){
  df %>%
    filter(!is.na(Market_Cap)) %>% 
    filter(Market_Cap > quantile(Market_Cap,0.05)) %>%
    filter(EY_Z < quantile(EY_Z,0.5,na.rm=TRUE) |
             Tot_Ret > quantile(Tot_Ret,0.5,na.rm=TRUE) |
             GP_Z > quantile(GP_Z,0.5,na.rm=TRUE) |
             VOL < quantile(VOL,0.5,na.rm=TRUE))
}

ALL_FACTOR_Model <- ALL_FACTOR_Selection %>% mutate(stocks = map(data,stocks))
```