---
title: "Stock selection for low Volatility portfolio"
author: "Kobus Viljoen"
date: "28 September 2016"
output: html_document
---
```{r}
knitr::opts_chunk$set(
  eval = FALSE)
```

##Necessary packages
```{r}
library(broom)
library(modelr)
library(ggplot2)
library(stringr)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(tibble)
```

##Grouping together the market cap and volatility values for each share

```{r}
# creating a function to group data according to their ticker for each fundamental
Fund <- function(df){
  df %>% bind_rows(.id="Ticker") %>%
  group_by(Ticker)
}

# map the function over the fundamentals and create a new tibble, fundamental all named Fund_all
Fund_all <- Fundamental_Data %>% mutate(FundData = map(Fund_Data,Fund))

# joining the market cap and volatility tibbles by date and ticker. Group by ticker and nest

Fund_VOL <- left_join(Fund_all %>% filter(fields == "CUR_MKT_CAP") %>% select(FundData) %>% unnest(),
Fund_all %>% filter(fields == "VOLATILITY_60D") %>% select(FundData) %>% unnest()) %>%
  group_by(Ticker) %>%
  nest()
```


## Selecting the stocks for each rebalancing date (quarterly dates)

```{r}
# The semi annual dates are extracted from the halfyearly price data that was extracted from bloomberg
# [[2]] is the data corresponding to quarterly dates
# date[14] corresponds to the rebancing date in June 2001.
dates <- close_prices$data[[2]] %>% 
  bind_rows(.id="Ticker") %>% 
  group_by(date) %>% 
  nest() %>%
  filter(date >= date[14]) %>%
  select(date)

#This function will run through all the semi-annual dates, selecting the corresponding fundamental data.
selection <- function(df1){
  all <- dates %>% mutate(sel = map(date,function(df){
    sel <- df1 %>% filter(date == df)
    tibble(date=sel$date , VOL = sel$VOLATILITY_60D,
           Market_Cap = sel$CUR_MKT_CAP)
  }))
  all$sel %>% bind_rows()
}

# The output:
# A tibble with all the shares in the first column, in the selection column: the share's fundamental value for each rebalancing date
VOL_model_Selection <- Fund_VOL %>% mutate(selection = map(data,selection))

# Now i need to group the output according to the quarterly dates.
# Once this is done, i can select the stocks according to some specified rule (Low volatility in this case)
# The result is a tibble with the first column, the rebalancing dates. The second column is a list of tibbles containing each share's info corresponding to that specific date.
VOL_Selection <- VOL_model_Selection$selection %>% 
  bind_rows(.id="Ticker") %>%
  mutate(Ticker = VOL_model_Selection$Ticker[as.numeric(Ticker)]) %>%
  group_by(date) %>%
  arrange(date) %>%
  nest()

# Filtering the top 50% of a factor (Factor Tilt) for each rebalancing date.
stocks <- function(df){
  df %>%
    filter(!is.na(Market_Cap)) %>% 
    filter(Market_Cap > quantile(Market_Cap,0.05)) %>%
    filter(VOL < quantile(VOL,0.5,na.rm=T))
}

VOL_Model <- VOL_Selection %>% mutate(stocks = map(data,stocks))
# I still need to filter through the most liquid stocks based on trading volume and trading ratio
```

Do I need to calculate Z-scores for the Volatility factor also, Will be quick to change as I already wrote a function to compute z-scores. This is on computer in stoc-selection.R file.
