---
title: "All models stock selection"
author: "Kobus Viljoen"
date: "20 October 2016"
output: html_document
---

```{r}
knitr::opts_chunk$set(
  eval = FALSE)
```

##Necessary packages
```{r}
library(broom)
library(modelr)
library(ggplot2)
library(stringr)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(tibble)
```

## Selecting stocks for value model
```{r}
stock_select <- function(df){
  df <- df %>% filter(!is.na(Market.Cap)) %>%
    filter(Market.Cap > quantile(Market.Cap,0.05)) %>%
    filter(!is.na(Sequential.ZScore.Current.Earnings.Yield.)) %>%
    filter(Sequential.ZScore.Current.Earnings.Yield. >
             quantile(Sequential.ZScore.Current.Earnings.Yield.,0.65)) %>%
    select(c(Ticker,GICS.Sector,Market.Cap,Earnings.Yield)) %>% 
    as_tibble()
}

cross_sec_Fund_data_VALUE <- cross_sec_Fund_data %>% mutate(stocks = map(Fundamental,stock_select))
```

## Selecting stocks for volatility model
```{r}
stock_select <- function(df){
  df <- df %>% filter(!is.na(Market.Cap)) %>%
    filter(Market.Cap > quantile(Market.Cap,0.05)) %>%
    filter(!is.na(Sequential.ZScore.60.Day.Annualized.Volatility.)) %>%
    filter(Sequential.ZScore.60.Day.Annualized.Volatility. <
             quantile(Sequential.ZScore.60.Day.Annualized.Volatility.,0.3)) %>%
    select(c(Ticker,GICS.Sector,Market.Cap,Volat.D.60)) %>% 
    as_tibble()
}

cross_sec_Fund_data_VOL <- cross_sec_Fund_data %>% mutate(stocks = map(Fundamental,stock_select))
```

## Selecting stocks for quality model
```{r}
stock_select <- function(df){
  df <- df %>% filter(!is.na(Market.Cap)) %>%
    filter(Market.Cap > quantile(Market.Cap,0.05)) %>%
    filter(!is.na(Sequential.ZScore.LF.Gross.Profit.)) %>%
    filter(Sequential.ZScore.LF.Gross.Profit. >
             quantile(Sequential.ZScore.LF.Gross.Profit.,0.35)) %>%
    select(c(Ticker,GICS.Sector,Market.Cap,Gross.Profit.LF)) %>% 
    as_tibble()
}

cross_sec_Fund_data_Quality <- cross_sec_Fund_data %>% mutate(stocks = map(Fundamental,stock_select))
```

## Selecting stocks for momentum model
```{r}
stock_select <- function(df){
  df <- df %>% filter(!is.na(Market.Cap)) %>%
    filter(Market.Cap > quantile(Market.Cap,0.05)) %>%
    filter(!is.na(Sequential.ZScore.1.Year.Total.Return.)) %>%
    filter(Sequential.ZScore.1.Year.Total.Return. >
             quantile(Sequential.ZScore.1.Year.Total.Return.,0.7)) %>%
    select(c(Ticker,GICS.Sector,Market.Cap,Total.Return.Y.1)) %>% 
    as_tibble()
}

cross_sec_Fund_data_MOM <- cross_sec_Fund_data %>% mutate(stocks = map(Fundamental,stock_select))
```

## Selecting stocks for Multi-Factor model
```{r}
stock_select <- function(df){
  df <- df %>% filter(!is.na(Market.Cap)) %>%
    filter(Market.Cap > quantile(Market.Cap,0.05)) %>%
    filter(!is.na(Sequential.ZScore.Current.Earnings.Yield.) &
             !is.na(Sequential.ZScore.1.Year.Total.Return.) &
             !is.na(Sequential.ZScore.LF.Gross.Profit.) &
             !is.na(Sequential.ZScore.60.Day.Annualized.Volatility.)) %>%
    mutate(Z_ALL = Sequential.ZScore.Current.Earnings.Yield. + Sequential.ZScore.1.Year.Total.Return. +
             Sequential.ZScore.LF.Gross.Profit. - Sequential.ZScore.60.Day.Annualized.Volatility.) %>%
    filter(Z_ALL >
             quantile(Z_ALL,0.4)) %>%
    select(c(Ticker,Short.Name,GICS.Sector,Market.Cap,Earnings.Yield,Total.Return.Y.1,Gross.Profit.LF,Volat.D.60)) %>% 
    as_tibble()
}

cross_sec_Fund_data_4Factor <- cross_sec_Fund_data %>% mutate(stocks = map(Fundamental,stock_select))
```