---
title: "Stock selection for momentum portfolio"
author: "Kobus Viljoen"
date: "29 September 2016"
output: html_document
---
```{r}
knitr::opts_chunk$set(
  eval = FALSE)
```

##Necessary packages
```{r}
library(broom)
library(modelr)
library(ggplot2)
library(stringr)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(tibble)
```


##Grouping together the market cap and volatility values for each share
```{r}
Fund <- function(df){
  df %>% bind_rows(.id="Ticker") %>%
  group_by(Ticker)
}

# map the function over the fundamentals and create a new tibble, fundamental all named Fund_all
Fund_all <- Fundamental_Data %>% mutate(FundData = map(Fund_Data,Fund))

# joining the market cap and volatility tibbles by date and ticker. Group by ticker and nest
Fund_MOM <- left_join(Fund_all %>% filter(fields == "CUR_MKT_CAP") %>% select(FundData) %>% unnest(),
 Fund_all %>% filter(fields == "PX_LAST") %>% select(FundData) %>% unnest()) %>%
   group_by(Ticker) %>%
   nest()
```


## Selecting the stocks for each rebalancing date (semi-annual dates)
```{r}
# The semi annual dates are extracted from the halfyearly price data that was extracted from bloomberg
# [[3]] is the data corresponding to semi-annual dates
dates <- close_prices$data[[3]] %>% 
  bind_rows(.id="Ticker") %>% 
  group_by(date) %>% 
  nest() %>%
  filter(date >= date[7]) %>%
  select(date)

selection <- function(df1){
  all <- dates %>% mutate(sel = map(date,function(df){
    sel <- df1 %>% filter(date <= df) %>% filter(date >= df - years(1))
    Tot_Ret <- log(tail(sel$PX_LAST,1)) - log(sel$PX_LAST[1])
    tibble(date = df , Tot_Ret_1Y = Tot_Ret[1],
           Market_Cap = sel %>% filter(date == df) %>% select(CUR_MKT_CAP) %>% as.numeric())
    }))
  all$sel %>% bind_rows()
}

# The output:
MOM_model_Selection <- Fund_MOM %>% mutate(selection = map(data,selection))

# Now i need to group the output according to the semi-annual dates.
# Once this is done, i can select the stocks according to some specified rule (High Momentum in this case)
MOM_Selection <- MOM_model_Selection$selection %>% 
  bind_rows(.id="Ticker") %>%
  mutate(Ticker = MOM_model_Selection$Ticker[as.numeric(Ticker)])

# The result is a tibble with the first column, the rebalancing dates. The second column is a list of tibbled containing each share's info corresponding to that specific date.
MOM_Selection <- MOM_Selection %>% 
  group_by(date) %>% 
  arrange(date) %>% 
  nest()

# Filtering the top 50% of a factor (Factor Tilt)
stocks <- function(df){
  df %>%
    filter(!is.na(Market_Cap)) %>% 
    filter(Market_Cap > quantile(Market_Cap,0.05)) %>%
    filter(Tot_Ret_1Y > quantile(Tot_Ret_1Y,0.5, na.rm = T))
}

MOM_Model <- MOM_Selection %>% mutate(stocks = map(data,stocks))
```


